apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-didm
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0054-tenant/tkrw-pr712-0075-0054-app/devfile-sample-didm@sha256:82a4e2ce1452e7b38aacfd281bc95fa1df12e83a5acbd44c2512bf9be6378e23
        name: my-nodejs
        resources: {}
status: {}
